---
- name: Prueba con Variables de ficheros externos
  hosts: rocky
  vars_files:
    - recursos/fichero1.yaml
    - recursos/fichero2.yaml
  tasks:
    - name: Variable del primer fichero
      debug:
        msg: "Este valor es del primer fichero --> {{ f1 }}"

    - name: Variable del segundo fichero
      debug:
        msg: "Este valor es del segundo fichero --> {{ f2 }}"
