---
- name: Trabajar con ficheros
  hosts: debian
  vars:
    fichero: "/tmp/prueba.txt"

  tasks:
    - name: Crear un fichero
      file:
        path: "{{fichero}}"
        state: "touch"

    - name: Cambiar permisos
      file:
        path: "{{fichero}}"
        owner: ansible
        group: ansible
        mode: "0777"
