---
- name: Prueba con Variables FACT
  hosts: rocky1
  
  tasks:
  - name: Ver variables FACT
    debug:
      msg: "Arquitectura  {{ansible_facts.architecture}} {{ansible_facts['bios_vendor']}} {{ansible_facts['all_ipv4_addresses'][0]}} "
